
const STATUS_LOADING = 'REQUEST_STATUS_LOADING'
const STATUS_SUCCESS = 'REQUEST_STATUS_SUCCESS'
const STATUS_ERROR = 'REQUEST_STATUS_ERROR'

export default {
    STATUS_LOADING,
    STATUS_SUCCESS,
    STATUS_ERROR
}